### ISSUE TITLE
老哥你不同账号都是用的同一个ips吗？

### ISSUE THREAD

**Issue by hhh2566** [clov616/microsoft-rewards#1]
如题

**Comment by clov616** [comment]
是的

**Comment by hhh2566** [comment]
我建议你最好分开来，因为我之前手动刷两个号的时候就是同用的同1 IP，最后面兑换的时候一个号直接被ban了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月23日(周四) 中午1:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [clov616/microsoft-rewards] 老哥你不同账号都是用的同一个ips吗？ (Issue #1)




 
是的
